"""
render_report.py – Generate HTML (for email) and Markdown (for archiving) reports.

Both formats follow the structure:
  - Global top-20 list ordered by importance
  - Each item shows: rank, category, title (EN + ZH), summary (EN + ZH), source link
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

import pytz

log = logging.getLogger(__name__)

BEIJING_TZ = pytz.timezone("Asia/Shanghai")

# Category display names (Chinese)
CATEGORY_ZH: dict[str, str] = {
    "AI": "人工智能",
    "Robotics": "机器人",
    "Space": "航空航天",
    "Science": "基础科学",
    "Physics": "物理学",
    "Biology": "生命科学",
    "Medicine": "医疗健康",
    "Chemistry": "化学",
    "Psychology": "心理学",
    "Social Sciences": "社会科学",
    "InfoEng": "信息工程",
    "Technology": "科技",
    "General": "综合",
}

# ── HTML template ─────────────────────────────────────────────────────────────

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{subject}</title>
<style>
  body {{ font-family: -apple-system, 'Segoe UI', Arial, sans-serif;
         background:#f5f7fa; margin:0; padding:0; color:#222; }}
  .container {{ max-width:720px; margin:24px auto; background:#fff;
               border-radius:10px; box-shadow:0 2px 12px rgba(0,0,0,.08); }}
  .header {{ background:linear-gradient(135deg,#1a237e,#283593);
             color:#fff; padding:32px 36px 24px; border-radius:10px 10px 0 0; }}
  .header h1 {{ margin:0 0 6px; font-size:1.6rem; letter-spacing:.5px; }}
  .header p  {{ margin:0; opacity:.85; font-size:.95rem; }}
  .body  {{ padding:28px 36px; }}
  .item  {{ border-left:4px solid #3f51b5; padding:14px 16px; margin-bottom:22px;
            background:#f8f9ff; border-radius:0 6px 6px 0; }}
  .rank  {{ display:inline-block; background:#3f51b5; color:#fff;
            font-size:.75rem; font-weight:700; padding:2px 8px;
            border-radius:3px; margin-right:8px; }}
  .cat   {{ display:inline-block; background:#e8eaf6; color:#3f51b5;
            font-size:.75rem; font-weight:600; padding:2px 8px;
            border-radius:3px; }}
  .title-en {{ font-size:1.05rem; font-weight:700; margin:8px 0 2px; color:#1a237e; }}
  .title-zh {{ font-size:1.0rem;  font-weight:700; margin:2px 0 8px; color:#283593; }}
  .summary  {{ font-size:.9rem; line-height:1.6; color:#444; margin-bottom:6px; }}
  .summary-en {{ margin-bottom:4px; }}
  .summary-zh {{ color:#555; }}
  .source {{ font-size:.82rem; color:#888; }}
  .source a {{ color:#3f51b5; text-decoration:none; }}
  .source a:hover {{ text-decoration:underline; }}
  .footer {{ text-align:center; font-size:.8rem; color:#aaa;
             padding:18px 36px; border-top:1px solid #eee; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📰 每日科技日报 · Daily Tech Brief</h1>
    <p>{date_beijing} · Top {count} 全球重要新闻 / Global Top Stories</p>
  </div>
  <div class="body">
{items_html}
  </div>
  <div class="footer">
    由 <a href="https://github.com/xiubing567/daily-brief" style="color:#aaa">daily-brief</a> 自动生成 ·
    Auto-generated by daily-brief<br>
    如需退订请联系发件人 / To unsubscribe, contact the sender
  </div>
</div>
</body>
</html>
"""

ITEM_HTML_TEMPLATE = """\
    <div class="item">
      <span class="rank">#{rank}</span>
      <span class="cat">{cat_zh} / {cat_en}</span>
      <div class="title-en">{title_en}</div>
      <div class="title-zh">{title_zh}</div>
      <div class="summary summary-en">📝 {summary_en}</div>
      <div class="summary summary-zh">📝 {summary_zh}</div>
      <div class="source">🔗 来源 / Source:
        <a href="{url}" target="_blank">{source_name}</a>
      </div>
    </div>"""

# ── Markdown template ─────────────────────────────────────────────────────────

MD_HEADER = """\
# 📰 每日科技日报 · Daily Tech Brief

> **日期 / Date**: {date_beijing}
> **共 {count} 条全球重要新闻 / {count} Global Top Stories**

---

"""

MD_ITEM = """\
## #{rank} [{cat_zh}/{cat_en}] {title_en}

**{title_zh}**

- 📝 **EN**: {summary_en}
- 📝 **中文**: {summary_zh}
- 🔗 **来源**: [{source_name}]({url})

---

"""


# ── Rendering helpers ─────────────────────────────────────────────────────────


def _escape_html(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _beijing_date_str() -> str:
    now_bj = datetime.now(tz=BEIJING_TZ)
    return now_bj.strftime("%Y年%m月%d日 %A")


def render_html(articles: list[dict]) -> str:
    date_str = _beijing_date_str()
    items_parts = []
    for art in articles:
        cat_en = art.get("category", "General")
        cat_zh = CATEGORY_ZH.get(cat_en, cat_en)
        items_parts.append(
            ITEM_HTML_TEMPLATE.format(
                rank=art.get("rank", "?"),
                cat_zh=_escape_html(cat_zh),
                cat_en=_escape_html(cat_en),
                title_en=_escape_html(art.get("title_en", art.get("title", ""))),
                title_zh=_escape_html(art.get("title_zh", "")),
                summary_en=_escape_html(art.get("summary_en", "")),
                summary_zh=_escape_html(art.get("summary_zh", "")),
                url=art.get("url", "#"),
                source_name=_escape_html(art.get("source_name", "")),
            )
        )

    subject = f"每日科技日报 {datetime.now(tz=BEIJING_TZ).strftime('%Y-%m-%d')}"
    return HTML_TEMPLATE.format(
        subject=subject,
        date_beijing=date_str,
        count=len(articles),
        items_html="\n".join(items_parts),
    )


def render_markdown(articles: list[dict]) -> str:
    date_str = _beijing_date_str()
    md = MD_HEADER.format(date_beijing=date_str, count=len(articles))
    for art in articles:
        cat_en = art.get("category", "General")
        cat_zh = CATEGORY_ZH.get(cat_en, cat_en)
        md += MD_ITEM.format(
            rank=art.get("rank", "?"),
            cat_zh=cat_zh,
            cat_en=cat_en,
            title_en=art.get("title_en", art.get("title", "")),
            title_zh=art.get("title_zh", ""),
            summary_en=art.get("summary_en", ""),
            summary_zh=art.get("summary_zh", ""),
            source_name=art.get("source_name", ""),
            url=art.get("url", "#"),
        )
    return md


def save_reports(
    articles: list[dict],
    output_dir: str = "reports",
) -> tuple[str, str]:
    """
    Save HTML and Markdown reports to disk.
    Returns (html_path, md_path).
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    date_tag = datetime.now(tz=BEIJING_TZ).strftime("%Y-%m-%d")

    html_content = render_html(articles)
    md_content = render_markdown(articles)

    html_path = os.path.join(output_dir, f"{date_tag}.html")
    md_path = os.path.join(output_dir, f"{date_tag}.md")

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    log.info("Saved HTML report → %s", html_path)
    log.info("Saved Markdown report → %s", md_path)
    return html_path, md_path


def get_email_subject() -> str:
    date_bj = datetime.now(tz=BEIJING_TZ).strftime("%Y-%m-%d")
    return f"📰 每日科技日报 {date_bj} · Daily Tech Brief"
